twig:
    default_path: '%kernel.project_dir%/templates'
    date:
        format: d/m/Y
        timezone: Europe/Paris
    number_format:
        decimals: 2
        decimal_point: ','
        thousands_separator: ' '
    form_themes:
        - 'core/form/_theme.html.twig'
